-- MySQL Script generated by MySQL Workbench
-- Sat Apr  5 02:46:46 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yueying
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yueying` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `yueying` ;

-- -----------------------------------------------------
-- Table `yueying`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yueying`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(200) NULL,
  `b_name` VARCHAR(200) NULL,
  `sell_date` TIMESTAMP NULL,
  `tip` TEXT NULL,
  `companyid` INT NULL,
  `circulation` BIGINT NULL,
  `duration` INT NULL,
  `income_rate` DECIMAL(10,0) NULL,
  `min_sub_amount` BIGINT NULL,
  `interest_ distribution_id` INT NULL,
  `invest_orientation_id` INT NULL,
  `xintuo_type_id` INT NULL,
  `income_explain` TEXT NULL,
  `pledge_object` VARCHAR(200) NULL,
  `pledge_rate` VARCHAR(20) NULL,
  `productinfo` TEXT NULL,
  `purpose_info` TEXT NULL,
  `risk_control_info` TEXT NULL,
  `payment_info` TEXT NULL,
  `guarantor_info` TEXT NULL,
  `financingpart_info` TEXT NULL,
  `depositary_info` TEXT NULL,
  `more_info` TEXT NULL,
  `insert_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '信托产品表';


-- -----------------------------------------------------
-- Table `yueying`.`iint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yueying`.`iint` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '利息分配方式表';


-- -----------------------------------------------------
-- Table `yueying`.`investorientation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yueying`.`investorientation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '投资方向表';


-- -----------------------------------------------------
-- Table `yueying`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yueying`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `introduce` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '信托公司表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
